# Generated by Django 5.1.7 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_register',
            name='pro_img',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
    ]
