# Generated by Django 5.1.7 on 2025-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_admin_register_pro_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('degree', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pro_pic', models.ImageField(default='', upload_to='profile_pics/')),
            ],
        ),
    ]
