# Generated by Django 5.1.7 on 2025-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_desc',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_4',
            field=models.TextField(default=''),
        ),
    ]
