# Generated by Django 5.1.7 on 2025-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_class',
            field=models.CharField(default='bi-palette', max_length=100),
        ),
    ]
