# Generated by Django 5.1.7 on 2025-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_services_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='icon_class',
            new_name='service_icon',
        ),
    ]
